### ISSUE TITLE
Encrypt for Auth

### ISSUE THREAD

**Issue by MarcusMann** [gin-gonic/gin#1002]
Hi,

Why do you use 64 Encryption and not 256?
For authentication

Thanks.

**Comment by javierprovecho** [comment]
@MarcusMann do you mean [`func BasicAuth(accounts Accounts) HandlerFunc`](http://godoc.org/github.com/gin-gonic/gin#BasicAuth)? That's because it is defined on the [`RFC 7617`](https://tools.ietf.org/html/rfc7617). Also, `base64` is not encryption but encoding. You shouldn't use it in not secure channels (ex, plain http)

**Comment by MarcusMann** [comment]
Hi @javierprovecho,

I would like to use Login to my project. Do you think feasible?

Thanks for reply

**Comment by javierprovecho** [comment]
@MarcusMann you may use https://github.com/gin-gonic/gin#using-basicauth-middleware or something more advanced and general purpose like https://github.com/RangelReale/osin, which is very easy to adapt into gin
