### ISSUE TITLE
not support this ?

### ISSUE THREAD

**Issue by jicg** [gin-gonic/gin#1132]
``` go
orderRouter := offline.Group("order")
{
	orderRouter.GET("", order.QueryOrders)
	orderRouter.POST("", order.Add)
	orderRouter.GET("/:id", order.GetById)
	orderRouter.PATCH("/:id", order.Patch)
	payRouter := orderRouter.Group("wxpay")
	{
	        payRouter.GET("/:id", order.WxPay)
	}
}
```
errors：
``` log
path segment 'wxpay/:id' conflicts with existing wildcard ':id' in path '/v1/offline/order/wxpay/:id'
```
why????

**Comment by nazwa** [comment]
This has been discussed so many times before. I suggest have a search for "wildcard" in issues.

It's a limitation of the underlying routing logic that doesn't rely on regular expressions for improved performance. In essence, all routes need to be "unique". `/:id` is is ambiguous in relation to `/wxpay/:id` because `/:id` potentially covers both paths.
