### ISSUE TITLE
[Q] Has gin a feature for url parameters?

### ISSUE THREAD

**Issue by sinnlosername** [gin-gonic/gin#1262]
Hi!

I'm currently using gorilla/mux as http framework. It got a feature where you can define url parameters as regex like:

```go
router.HandleFunc("/test/{hexCode:[A-F0-9]{1,5}}", <func>)
```

In this function you can get the url parameters using `mux.Vars(req)["hexCode"]`. If the request doesn't match the regex it will result in a 404.

Is there a similar feature in gin?

**Comment by dalu** [comment]
No
It uses httprouter or rather it's own adaption of it.
And httprouter doesn't support regexp path params.
That's why it claims to be the fastest golang http router. But since it doesn't have conditions for pathparams you can imagine how much weight this claim has.
You have to do validity checking in your handler

**Comment by skrps** [comment]
Related: #229 #680

**Comment by thinkerou** [comment]
as @skrps pointed, the issue duplicated, if you have any problem welcome reopen it, thanks!
