### ISSUE TITLE
every request not call  gin.HandlerFunc method

### ISSUE THREAD

**Issue by aolmez** [gin-gonic/gin#1309]
Hi

i use gin.HandlerFunc method but first request call handler but when call context.Redirect in handler   then  not call method.
Can you help me?
```

authorized := server.Engine().Group("/home")
authorized.Use(attributes.RequireLogin())
{
authorized.GET("", controller.Index)
}


```
```
func RequireLogin() gin.HandlerFunc {
	return func(c *gin.Context) {
		fmt.Println("RequireLogin")
		c.Next()
	}
}
```

**Comment by sosedoff** [comment]
If you're hitting any endpoint like `/home/blah` and your router does not have that path registered, the middleware will not be called since the route does not exist. Also, your example does not include any reference to `context.Redirect` call, so it's not clear what you're trying to do. 

Also, make sure to return from the middleware after you call `Redirect` as it will not automatically terminate the request chain. Here's an example for you:

```go
package main

import (
	"log"

	"github.com/gin-gonic/gin"
)

func requireLogin(c *gin.Context) {
	log.Println("Require Login")

	token := c.Query("api_token")

	if token == "" {
		log.Println("Api token is not provided, redirecting...")
		c.Redirect(302, "/login")
		return
	}
	if token != "foobar" {
		log.Println("Invalid token")
		c.Redirect(302, "/login")
		return
	}

	c.Next()
}

func handleHome(c *gin.Context) {
	c.JSON(200, gin.H{"home": "sweet home"})
}

func main() {
	router := gin.Default()

	home := router.Group("/home")
	home.Use(requireLogin)
	home.GET("", handleHome)

	router.Run(":5000")
}
```

**Comment by thinkerou** [comment]
closing
