### ISSUE TITLE
WriteHeaderNow on Abort

### ISSUE THREAD

**Issue by 1995parham** [gin-gonic/gin#1355]
https://github.com/gin-gonic/gin/blob/bf7803815b0baa22ff7a10457932882dfbf09925/context.go#L129

Why we need writing header on abort? by doing this c.JSON() for writing errors in `ErrorLogger` failed to set Content-Type to `application/json`.

**Comment by matthewmcneely** [comment]
Having this issue too with a custom error logger that returns a JSON object representing the error details

**Comment by delphinus** [comment]
How about `c.AbortWithStatusJSON()`?

**Comment by matthewmcneely** [comment]
Thanks for the suggestion.... tried that in my error handler but that's no joy. Problem is that in the controller code, AbortWIthError kicks everything off, and it immediately writes headers leaving the middleware out of the picture.

If you set the header prior to calling AbortWithError, then you beat it to the punch. But this is more of a workaround than a solution

**Comment by 1995parham** [comment]
I think this line of code removes every chance to change `Content-Type`.

**Comment by delphinus** [comment]
I see.  At first, `c.Abort` does not write headers, but `c.AbortWithStatus`, `c.AbortWithError`, `c.AbortWithStatusJSON` do.

Then probably you say, “Is it necessary that those `c.AbortWithXXX`'s write headers?”.  The answer is **Yes**.

Because they are added against methods for regular responses, that is, `c.HTML`, `c.String`, `c.JSON`, and so on.  They also write outputs and status with headers, so `c.AbortWithXXX` families should do.

```go
func someHandler(c *gin.Context) {
  if err := someFunc(...); err != nil {
    // write headers and abort
    _ = c.AbortWithError(500, err)
    return
  }
  // write headers and valid HTML
  c.HTML(200, "valid-html", nil)
}
```

So, if you want to return JSON in middlewares as @matthewmcneely says, I suggest to use `c.Error` and `c.Abort` individually.

```go
func someHandler(c *gin.Context) {
  if err := someFunc(); err != nil {
    _ = c.Error(err)
    c.Abort()
    return
  }
  ...
}

func loggerMW() gin.HandlerFunc {
  return func(c *gin.Context) {
    c.Next()
    if c.IsAborted() && !c.Writer.Written() && len(c.Errors) > 0 {
      c.JSON(500, gin.H{"errors": c.Errors})
    }
  }
}

...

r := gin.New()
r.GET("/", loggerMW(), someHandler)

...
```

This example fixes status to `500`.  If you want to specify this in handlers, you can choose several ways...

* `c.Status()` / `c.Writer.Status()`
* `c.Error().SetMeta()` / `err.Meta`
* `c.Set()` / `c.Get()`
* ...

**Comment by 1995parham** [comment]
Thanks for your explanation
