### ISSUE TITLE
Question: What structure folder in gin with big scale project ? 

### ISSUE THREAD

**Issue by thuandoan274** [gin-gonic/gin#1435]
I don't know to organize folder with controllers, services, models. How to make them working well without IMPORT CYCLE because I reuse code so much.
This is my structure project
![screenshot_1](https://user-images.githubusercontent.com/39752625/42885972-9d4722d0-8acc-11e8-9df2-d3a94c4f0864.png)

**Comment by syssam** [comment]
Golang is free, for me,
-app
--controllers
--models
--middlewares
-config
-database
-lang
-lib
-routes
-main.go

**Comment by thuandoan274** [comment]
My file service has more than 300 lines. I wanna split my services to multiple folder for each service

**Comment by syssam** [comment]
I see your project structure is fine.This project structure I used at React before.
You said "IMPORT CYCLE", could you explain more?

**Comment by thuandoan274** [comment]
Thật means you has 2 services like review and business. You import business in review so you can't import review in business

**Comment by syssam** [comment]
I do know this idea is good or not, because I did not this issue before.

You can create new package as C will import both review and business, it creates an instance of review and passes it to business or add some services which will case "IMPORT CYCLE" issue, then passes it to review and business.

On the other hand, I saw someone will using unsafe.pointer to solved this problem.
