### ISSUE TITLE
Panic runtime error: index out of range in context.go:108

### ISSUE THREAD

**Issue by Collapsik** [gin-gonic/gin#1678]
After commit b97ccf3a43d2901d295870b5876277bf478a4909 I catch panic that never been before. In my case length of c.handlers equal 1 and c.index equal 1.

![image_2018-12-03_11-55-57](https://user-images.githubusercontent.com/16224266/49366578-4ed68400-f6f2-11e8-9ddf-96a4723c1daf.png)

**Comment by thinkerou** [comment]
@Collapsik can you post your test code? I use it reproduce the issue, thanks!

**Comment by Kirides** [comment]
I get the same / a simmilar issue. It appears to happen _after_ my handler returned

Code: https://pastebin.com/kM6UwyB3

**Comment by thinkerou** [comment]
Sorry, I still can't reproduce it.

**Comment by vkd** [comment]
I have reproduced it.

It happens because during [`func (c *Context) Next() {`](https://github.com/gin-gonic/gin/blob/master/context.go#L106) method it iterates over c.handlers with precalculated size of `c.handlers`.
```
func (c *Context) Next() {
	c.index++
	for s := int8(len(c.handlers)); c.index < s; c.index++ {
		c.handlers[c.index](c)
	}
}
```
But [`func (group *RouterGroup) StaticFS(...) ... {`](https://github.com/gin-gonic/gin/blob/master/routergroup.go#L172) rewrite `c.handlers` to slice with other size than we calculated in `c.Next(...)` (https://github.com/gin-gonic/gin/blob/master/routergroup.go#L198)
```
func (group *RouterGroup) createStaticHandler(relativePath string, fs http.FileSystem) HandlerFunc {
	...
	return func(c *Context) {
		...
		// Check if file exists and/or if we have permission to access it
		if _, err := fs.Open(file); err != nil {
			c.Writer.WriteHeader(http.StatusNotFound)
			c.handlers = group.engine.allNoRoute
			// Reset index
			c.index = -1
			return
		}

		fileServer.ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by thinkerou** [comment]
#1744
