### ISSUE TITLE
JSON formatting - Feature

### ISSUE THREAD

**Issue by rabarar** [gin-gonic/gin#177]
Would be nice to implement JSON render option similar to Martinit's render option that allows for Human-readable JSON Formatting on json output

**Comment by techjanitor** [comment]
In Martini render this is an option in the initialization struct for the middleware. It just changes Marshal to MarshalIndent:
https://github.com/martini-contrib/render/blob/master/render.go#L126

I agree it would be a nice feature to have with c.JSON

**Comment by jamie-stackhouse** [comment]
If this is added, the default should be to not indent the JSON.

**Comment by achedeuzot** [comment]
Maybe enable indented JSON in development mode ?

**Comment by jamie-stackhouse** [comment]
There are times in development though where you will want to test stripped JSON output with gzip turned on so regardless of which .

I think Martini's approach would be ideal at least in our case. 

Configuration during setup of Gin. Perhaps SetMode could be extended to also accept a configuration object, this way you can set prod mode, but still enable indented JSON?

**Comment by javierprovecho** [comment]
Hi everyone, I have been looking at this request, and here are my suggestions on how to implement.

- Using variable state in mode.go to output indented JSON only in dev mode.
- Adding a strin
Hi everyone, I have been looking at this request, and here are my suggestions on how to implement.

- Using variable state in mode.go to output indented JSON only in dev mode.
- Adding a string after obj in `c.JSON(code int, obj...)`. It would be detected same as `func (_ plainRender) Render(...) error {}`. I copied it below.

```go
func (_ plainRender) Render(w http.ResponseWriter, code int, data ...interface{}) error {
	writeHeader(w, code, "text/plain")
	format := data[0].(string)
	args := data[1].([]interface{})
	var err error
	if len(args) > 0 {
		_, err = w.Write([]byte(fmt.Sprintf(format, args...)))
	} else {
		_, err = w.Write([]byte(format))
	}
	return err
}
```

I prefer the 2nd one because it DOES NOT break any compatibility with previous code. What do you think? Please @jamie-stackhouse @achedeuzot @techjanitor @rabarar @kishorevaishnav, share your thoughs.g after obj in `c.JSON(code int, obj...)`. It would be detected same as `func (_ plainRender) Render(...) error {}`. I copied it below.

```go
func (_ plainRender) Render(w http.ResponseWriter, code int, data ...interface{}) error {
	writeHeader(w, code, "text/plain")
	format := data[0].(string)
	args := data[1].([]interface{})
	var err error
	if len(args) > 0 {
		_, err = w.Write([]byte(fmt.Sprintf(format, args...)))
	} else {
		_, err = w.Write([]byte(format))
	}
	return err
}
```

I prefer the 2nd one because it DOES NOT break any compatibility with previous code. What do you think? Please @jamie-stackhouse @achedeuzot @techjanitor @rabarar @kishorevaishnav, share your thoughs.

**Comment by jamie-stackhouse** [comment]
My only thought is that adding another type assertion to every call for something that I would argue is useful in a very small percentage of cases isn't the road I would go down. I'd prefer writing for production and handling niceties inside a single if based off configuration.

On one extreme,
I really only see a single way to implement it without affecting performance, and that would be using tags. You could technically pull this function into it's own file, and define it's functionality based off a build constraint.

I'd be interested to know what prompted the request, since most client tools have the ability to format JSON on the other side (Chrome/Firefox both have plenty of JSON plugins), and for those that don't use a proxy tool such as Charles could inspect the request on the wire and give you a pretty printed version as well.

**Comment by jamie-stackhouse** [comment]
As well, I'm against this, since supporting indented JSON easily makes the ability to add overhead easy. The worst case I've seen is stripping just whitespace and not even doing gzip saved about ~25% of a 700k JSON document in response size. This was something that was being served to over 300 thousand people, every hour. This change alone saved the company thousands of dollars in CDN bandwidth fees.

The ability to accomplish this already exists in the API, and making it simpler I feel is doing a disservice to the developer, and to their potential customers/wallets.

**Comment by javierprovecho** [comment]
Well, after looking more extensively intro this, I decided not to implement it. As @jamie-stackhouse many clients (browsers, api fetchers, ...) have indentation plugins. As for default, Gin should be as fast as possible, and that also means to use less bandwidth.

**Comment by tritonresearch** [comment]
Can you recommend a clean way of adding JSON indentation? Does this mean it has to be done manually before each c.JSON response?

**Comment by itsjamie** [comment]
The clean way I would propose would be writing a function to handle this, and mimic the c.JSON interface.

```go
func WriteIndented(c *gin.Context, val interface{}) {
  //.. call json.MarshalIndent()
 //.. call c.Writer.Write()
}
```

If you don't mind me asking, why do you need to indent your JSON?

**Comment by tritonresearch** [comment]
Indeed, given browser plugins for JSON indentation this turned out to not be necessary.

**Comment by manucorporat** [comment]
The render system in Gin is pluggable, you can create your own render, see the render package.

```go
c.Render(myJSONRender, 200, obj)
```

Done!

**Comment by manucorporat** [comment]
https://github.com/gin-gonic/gin/commit/abcc6d9dec17b1fd66f07aa2a0202eda8954dd39

**Comment by manucorporat** [comment]
@rabarar https://github.com/gin-gonic/gin/blob/3df5dfdb7fe54cbe4c20443ea9f08316b10ae027/context.go#L331-L335
