### ISSUE TITLE
RunTLS() Modification Feature

### ISSUE THREAD

**Issue by rabarar** [gin-gonic/gin#178]
It would be nice to separate the ListenAndServeTLS() into two steps that would allow more control over starting and stopping server instances.

Maybe something like:
g.ListenTLS()  returns a listener
and
g.Server(listener) to serve the gin Engine handlers

This would allow one to wrap a control channel around a listener to do things like graceful shutdowns/cleanups.

**Comment by javierprovecho** [comment]
@rabarar I finally understanded your request (http://golang.org/src/net/http/server.go?s=55253:55321#L1843) but because of flexibility of Gin, this is more oriented to a package for [gin-gonic/contrib](https://github.com/gin-gonic/contrib). As same as httprouter, Gin's Engine variable is exposed so you can use it anywhere you like to initialize the server. Closing this issue for now.

**Comment by rabarar** [comment]
Sounds good.
