### ISSUE TITLE
Are you still  in development?

### ISSUE THREAD

**Issue by le2014** [gin-gonic/gin#201]
Why so slow to update?
Are you going to give up this project?

**Comment by javierprovecho** [comment]
Hello @le2014 and everyone who read this message,

Both the developers of this project, @manucorporat and me, are studying at university. That's why a project we almost developed in summer, now is getting even slower.

As you can see, I tried to release pressure of issues and pull requests in the very last days of the year. But I can't focus 100% on this, because my exams (and @manucorporat too) are all between last week of January and first week of February.

Also, is my desire to not only maintain but grow this awesome community around Gin-Gonic. For now, I just can say you that until the first week of February, I'm not able to work on the proyect, but I'm reading every and each one of the issues and pull requests from both repositories (main and contrib) that arrive to my inbox.

Hope I had given enough clarification, and sorry for all this time of inactivity. Have a good day.

PD: Dont close this issue until I return to activity, so others can read it. Thank you.

cc/ #186

**Comment by javierprovecho** [comment]
@le2014 please check #204. Thank you in advance.

**Comment by le2014** [comment]
Thank you!
