### ISSUE TITLE
Gin router functionality is so poor ( i am fan of gin but i have to say , so sorry guys.) , it is meant for creating rest apis , but no native support for CORS handling.

### ISSUE THREAD

**Issue by VJOfficial** [gin-gonic/gin#211]
Hello , i seriously having problem handling CORS stuff. there is no detailed routing available , not cors support by default , gin is not usable without these functionality. do something guys.

**Comment by olebedev** [comment]
@webgini check this out https://github.com/gin-gonic/contrib/blob/master/secure/example/example.go

**Comment by webgini** [comment]
not working :(

**Comment by webgini** [comment]
![deepinscreenshot20150207230732](https://cloud.githubusercontent.com/assets/5981019/6093035/4d0106b6-af1e-11e4-8edf-554a3143d31a.png)

**Comment by webgini** [comment]
![deepinscreenshot20150207231110](https://cloud.githubusercontent.com/assets/5981019/6093042/aec46f00-af1e-11e4-86c3-fac4d71a8cec.png)

**Comment by webgini** [comment]
and i am talking about here is , doing request from different domain , not same domain. and thnks for giving answer.

**Comment by matejkramny** [comment]
You're getting CORS issue, so i suggest you write some middleware to add the header

```
r.Use(func (context *gin.Context) {
  // add header Access-Control-Allow-Origin
  context.Writer.Header().Add("Access-Control-Allow-Origin", "*")
  context.Next()
})
```

**Comment by webgini** [comment]
but then i need to define OPTIONS method for every route i define. and that
is not practical solution , that should be inside framework , i guess.
because without defining options method for route 405 error will throw.

On Sat, Feb 7, 2015 at 11:20 PM, Matej Kramny <notifications@github.com>
wrote:

> You're getting CORS issue, so i suggest you write some middleware to add
> the header
>
> r.Use(func (context *gin.Context) {
>   // add header Access-Control-Allow-Origin
>   context.Writer.Header().Add("Access-Control-Allow-Origin", "*")
>   context.Next()
> })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gin-gonic/gin/issues/211#issuecomment-73374630>.
>



-- 

[image: --]

Vijay Bambhaniya
[image: http://]about.me/vbambhaniya
<http://about.me/vbambhaniya?promo=email_sig>

**Comment by matejkramny** [comment]
You don't, the browser does that automatically to check for CORS headers. Its called the 'preflight' request.

**Comment by webgini** [comment]
i tried it dude. without options handler in server , browser shows error ,
and with handler it works just fine. i am doing it now.

On Sat, Feb 7, 2015 at 11:32 PM, Matej Kramny <notifications@github.com>
wrote:

> You don't, the browser does that automatically to check for CORS headers.
> Its called the 'preflight' request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gin-gonic/gin/issues/211#issuecomment-73375173>.
>



-- 

[image: --]

Vijay Bambhaniya
[image: http://]about.me/vbambhaniya
<http://about.me/vbambhaniya?promo=email_sig>

**Comment by nimolix** [comment]
Add CORS middleware and define following route to enable CORS for every other routes

```go
	app.OPTIONS("/*cors", func(c *gin.Context) {
		// Does nothing!
	})
```

**Comment by jamie-stackhouse** [comment]
Gin does not register routes for you. Nor should it, in my opinion. If one wishes to have a slightly more declarative rather than explicit registration, they could easily build a middleware similar to the contrib cors package that determines based upon interface support if it should register an OPTIONS Preflight handler.

```
type Preflighter interface {
   Preflight(*gin.Context) 
}
```

For specific implementation...
If you want to opt-in to supporting CORS requests (which not all servers / resources / pages should!), then you need to add a OPTIONS request for that route, which responds appropriately. As @matejkramny said, this is called a preflight request, which is the browser (the client) asking the server if it would allow it to access this information from a different origin.

You can expect a few things in your implementation, the client may add some headers that you can inspect..

```
Origin: http://yourdomain.com
Access-Control-Request-Method: POST
Access-Control-Request-Headers: X-Custom-Header
```

To which you would need to response with at least the following for the actual request to be sent...

```
Access-Control-Allow-Origin: http://yourdomain.com
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: X-Custom-Header
```

**Comment by javierprovecho** [comment]
@webgini sorry for delay.

Gin uses httprouter engine as routing. It allows that speed because of its incredible optimization.

So why not to use httprouter and use Gin? Gin complements httprouter by adding a great layer of support to middlewares. Like some of the answers before, you can make the api of your dreams, with some custom middlewares.

If we start to add "native" support to all the techniques available, there will be so much overhead on each request, that it will break those speed records.

**Comment by itsjamie** [comment]
Optionally you can implement CORS as a middleware if you want. An example implementation is here.. http://github.com/itsjamie/gin-middleware-cors

**Comment by itsjamie** [comment]
The above is a fork, some of the documentation doesn't match unfortunately. 

@manucorpat, perhaps we could talk about bringing it into the contrib repo?

**Comment by hugowetterberg** [comment]
This is the (ALLOW ALL THE THINGS!) middleware that I use for CORS handling where I just want to open up completely:

```go
// LiberalCORS is a very allowing CORS middleware.
func LiberalCORS(c *gin.Context) {
	c.Header("Access-Control-Allow-Origin", "*")
	if c.Request.Method == "OPTIONS" {
		if len(c.Request.Header["Access-Control-Request-Headers"]) > 0 {
			c.Header("Access-Control-Allow-Headers", c.Request.Header["Access-Control-Request-Headers"][0])
		}
		c.AbortWithStatus(http.StatusOK)
	}
}
```

**Comment by starchou** [comment]
in gin version v1.0rc2 cors middleware can't work

https://github.com/itsjamie/gin-cors
https://github.com/gin-contrib/cors

both return 404
