### ISSUE TITLE
Is there a error when importing "github.com/go-playground/validator/v10"

### ISSUE THREAD

**Issue by Daghlny** [gin-gonic/gin#2151]
I think it should be "github.com/go-playground/validator.v10"

**Comment by Daghlny** [comment]
I use govendor for a project, and it cannot fetch "github.com/go-playground/validator/v10".

**Comment by thinkerou** [comment]
@Daghlny master branch? now the master branch don't support govendor.

**Comment by ivan-californias** [comment]
Same issue here:
```
go get -v -u github.com/gin-gonic/gin 
github.com/gin-gonic/gin (download) 
github.com/gin-contrib/sse (download) 
github.com/go-playground/validator (download) 
package github.com/go-playground/validator/v10: cannot find package "github.com/go-playground/validator/v10" in any of: 
    /usr/lib/golang/src/github.com/go-playground/validator/v10 (from $GOROOT) 
...
```

**Comment by Daghlny** [comment]
Ok, 

> @Daghlny master branch? now the master branch don't support govendor. #2148

Thanks

**Comment by alexxsanchezm** [comment]
Hello, I got this issue when deploying my project to google cloud, since I read this v10 directory not longer exists, I tried to reinstall gin to get a fresh version but got the same error. 
So I though the v10 is just an old transition version for the validator and maybe a symlink can fix it.

And yes, I know it's too hacky and I don't really know the side effects, but this what I did:
````
$cd $GOPATH/src/github.com/go-playground/validator/
$ln -s . v10
````

After that I just run my deploy script and worked. I think the underlaying problem gin is referencing that old v10 and needs to be updated.
