### ISSUE TITLE
Where can i learn gin

### ISSUE THREAD

**Issue by dijam8** [gin-gonic/gin#2369]
i want to learn gin framework 
i am new to programing and i want to learn gin so i can build websites with golang 
and i dont find any real useful sorce of  raw learning website 
can you lead me to some gin learning resorces   
 i think that you shold have a website with a docs section

**Comment by yakuter** [comment]
Hello @dijam8 gin's README file is the best document to learn gin
https://github.com/gin-gonic/gin/blob/master/README.md

However, because you are new to programming, first you should work about "what is API?" question. Gin is a backend tool to write API.

Then there are good blog posts and example repos on how to write API with gin. Some of them are:

https://github.com/eddycjy/go-gin-example
https://blog.logrocket.com/how-to-build-a-rest-api-with-golang-using-gin-and-gorm/
https://medium.com/@thedevsaddam/build-restful-api-service-in-golang-using-gin-gonic-framework-85b1a6e176f3

**Comment by appleboy** [comment]
1. website: https://gin-gonic.com/
2. more example: https://github.com/gin-gonic/examples
3. gin middleware: https://github.com/gin-contrib
4. more project using gin: https://gin-gonic.com/docs/users/
5. GitHub Search for Gin keyword: https://github.com/search?l=Go&q=gin&type=Repositories
