### ISSUE TITLE
 undefined: http.SameSite

### ISSUE THREAD

**Issue by sriharikapu** [gin-gonic/gin#2437]
## Description

Installation failure

## How to reproduce

```
sudo go get -u github.com/gin-gonic/gin
```

## Expectations

This is a dependency for one of my projects

## Actual result
![image](https://user-images.githubusercontent.com/6247133/87858131-4b385500-c949-11ea-8d98-ea55d47c76cc.png)

```

## Environment

- go version: go version go1.10.4 linux/amd64
- gin version (or commit ref): go version go1.10.4 linux/amd64
- operating system: ubuntu 18

**Comment by 2HgO** [comment]
The http.SameSite type was introduced in go1.11, that's why your go version cannot install the latest gin version. The earliest gin version that does not use this type is #2109 so you should probably install that or an even earlier version instead. As outlined in the docs, the latest gin version requires go1.11+
