### ISSUE TITLE
REST routing, optional params

### ISSUE THREAD

**Issue by akwiatkowski** [gin-gonic/gin#251]
Hello.

I wanted to create an rest json api, but I'm not sure is it possible in current version.

There is an empty param in example below.

```
r.GET("/api/meas/:name.json", func(c *gin.Context)
c.Params.ByName("name")
```

I have not pretty workaround:

```
r.GET("/api/meas/:name/.json", func(c *gin.Context)
c.Params.ByName("name")
```

Optional params in routing would be quite useful, I think.

**Comment by itsjamie** [comment]
@akwiatkowski, you should be able to write the route as ```/api/meas/:name```.

Inside the route, you can pull the name parameter and split on the last period. You would be able to look for these suffixes then.

I'd likely implement that as a middleware that set the response type in the context for future lookup.

However, if it fits your client (you can reasonable expect them to be able to set headers), I'd suggest using the Accept header for this rather than URL suffixes.

**Comment by thinkerou** [comment]
@akwiatkowski please see https://github.com/gin-gonic/gin#parameters-in-path, gin have supported.
