### ISSUE TITLE
wildcard path param

### ISSUE THREAD

**Issue by nnntlh** [gin-gonic/gin#2754]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

# Description
      wildcard path param ,url not found
  
## How to reproduce

```
package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

func handler(c *gin.Context) {
	fmt.Println(c.Params)
}

func main() {
	g := gin.Default()
	g.GET("/:resources/:name", handler)
	g.GET("/:resources", handler)
	g.GET("/namespaces/:namespace/:resources/:name", handler)
	g.GET("/namespaces/:namespace/:resources", handler)
	g.Run(":9090")
}

```

## Actual result

```
$ curl http://localhost:9000/namespaces/apps
404 page not found
```

## Environment

- go version: 1.16
- gin version (or commit ref): 1.7.2
- operating system: Ubuntu 20.04.2 LTS

**Comment by nnntlh** [comment]
I have already checked #2706 ,But it didn't solve my problem

**Comment by myml** [comment]
What you up to?
Maybe you can use `curl http://localhost:9000/namespaces/a_name/apps`

**Comment by appleboy** [comment]
duplicated of https://github.com/gin-gonic/gin/issues/2762 ?

**Comment by rw-access** [comment]
This looks like it might be different from #2762.

This particular case is actually not a bug but is working as designed. Basically each path element is checked, one at a time. Since `/namespaces` matched a full element in the path, the `:resources` wildcard will not match.

If you want, you can explicitly add a route for `/namespaces/:namespace` to hit the same handler as `/:resources/:name`

I think this ultimately comes down to a documentation thing. We don't have much documentation about how wildcards mix with exact paths, and should probably improveme it.

**Comment by appleboy** [comment]
@nnntlh 

```go
package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

func handler(c *gin.Context) {
	fmt.Println(c.Params)
}

func main() {
	g := gin.Default()
	g.GET("/:resources/:name", handler)
	g.GET("/:resources", handler)
	g.GET("/namespaces/:namespace", handler)
	g.GET("/namespaces/:namespace/:resources/:name", handler)
	g.GET("/namespaces/:namespace/:resources", handler)
	g.Run(":9090")
}

```

base on [the comment](https://github.com/gin-gonic/gin/issues/2754#issuecomment-868214177)
