### ISSUE TITLE
What's in a name

### ISSUE THREAD

**Issue by wenyekui** [gin-gonic/gin#297]
Type `gin.H`  is an alias of `map[stirng]interface{}`, what is `H` named for?  And why is framework named as `gin`?  Very curious.

**Comment by manucorporat** [comment]
gin.H is used a lot of times, people use it inlined in their codes:
```go
c.JSON(200,  gin.H{
    "foo": "bar",
})
```

that's the reason a short name is needed. Even though you don't have to use it.
Why `H`? because it stands for **H**ashmap. I could have named it `gin.M` but... I didn't :)

Gin, it is just that, a name, since there are many `routers`, I can't name it "router", it needs a name! and it had to be short because it is going to be all around the people's code. Also, when we started the Gin was based in the design of another popular web framework called "martini".
