### ISSUE TITLE
go get -u github.com/gin-gonic/gin can not install go gin

### ISSUE THREAD

**Issue by aswallz** [gin-gonic/gin#3125]
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2": https fet
ch: Get "https://gopkg.in/yaml.v2?go-get=1": x509: certificate has expired or is
 not yet valid:

**Comment by Anthony-Bible** [comment]
We ran into this using a really old operating system or an unupdated one because it doesn't or hasn't removed the expired let's encrypt root certificates. https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

You should verify your operating system is updated and/or has the proper certificates

**Comment by aswallz** [comment]
i solve this issue by downloading github xode and copy it to go root path
