### ISSUE TITLE
Faster JSON Serialization

### ISSUE THREAD

**Issue by EmergentBehavior** [gin-gonic/gin#344]
This is more of a feature request/exploration, but I'm wondering if Gin could be made even faster by using [`ffjson`](https://journal.paul.querna.org/articles/2014/03/31/ffjson-faster-json-in-go/). Apparently it's 2-3x faster than `encoding/json` because it doesn't use reflection. Repo: https://github.com/pquerna/ffjson

**Comment by manucorporat** [comment]
ffson generates static code for MarshalJSON() and MarshalJSONBuf(). the standard json package already tries to call the MarshalJSON() method before using reflexion.

So if you use ffson you will already get faster rendering performance. Probably not the fastest possible since the optimized `MarshalJSONBuf()` method will not be used.

We could implement a super lightweigth wrapper to call MarshalJSONBuf() but including the whole package seems like a lot of overhead.

**Comment by itsjamie** [comment]
@EmergentBehavior I think this could be implemented as a custom renderer ffjson? 

@manucorporat would that make sense?

This would allow you to change the behaviour to skip the calls to the json package and implement the "Tips" that the ffjson package mentions for reducing GC pressure.

**Comment by Allendar** [comment]
I would like to remark that doing some tests with a 100 user JSON objects in my system like so:

**Gin**
```
c.JSON(200, gin.H{
	"errors": []int{},
	"users":  users,
})
```

**ffjson**
```
output, err := ffjson.Marshal(&users)
if nil != err {
	panic(err)
}
c.Writer.Write(output) // All my output is JSON so I don't really care to much for setting the Conent-Type header explicitly
```

Both examples for this test are without type hinting and based on `map[string]interface{}`. Here are the results (output JSON accumulated is ~16kb):

`Gin: 552912 ns/op`

`ffjson:  550584 ns/op`

The differences are practically unnoticeable. By the time of creating this issue it might've been true tho, because in the past `ffjson` was really was faster than the built-in `json`.

Final note; the above results aren't always stable. When you have different loads on your installation both `c.JSON()` and `ffsjon.Marshal` approaches will bump around like crazy, easily ranging from `538092 ns/op` to as slow as `1177567 ns/op`. Even tho benchmarking seems reliable. I would always be pessimistic in doing this and taking the worse end of the spectrum for your total performance calculations. Saying your API can do 15k requests p/second in your benchmarks and then finding out your customers hardly hit `6k` requests tops on their real-world tests would be quite an embarrassment :P.

**Comment by javierprovecho** [comment]
we just switched to [jsonite](https://github.com/json-iterator/go) (see #990)
