### ISSUE TITLE
install failed on latest version

### ISSUE THREAD

**Issue by widnyana** [gin-gonic/gin#345]
I was succesfully installing gin few weeks ago, now I setup a new project and try to install it again via vendoring, I didnt use any third-party golang dependency manager.

and I got this error when echoing `$ go get github.com/gin-gonic/gin` on my terminal
```
# github.com/gin-gonic/gin
src/github.com/gin-gonic/gin/context.go:369: cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
        sse.Event does not implement render.Render (missing Render method)
>>> elapsed time 39s

```

my $GOPATH is `~/Code/golang/webstuff` and $GOROOT reside on `~/bin/go`

thank you for your awesome stuff, really love it! :)

**Comment by widnyana** [comment]
sorry my bad, didnt notice the update on `sse` repo. closed as invalid :)

**Comment by eexit** [comment]
Okay, I had the same issue and I had to guess what was going on.
Since it's not written explicitly, I'll do it: 

➡️  To fix the issue, update `github.com/manucorporat/sse` to the latest.

If you are using Glide, remove the references (`gin` + `sse`)  in the `glide.yaml` and  run `glide get github.com/gin-gonic/gin`.
