### ISSUE TITLE
`golang.org/x/net`  < 0.17.0 security vulnerability

### ISSUE THREAD

**Issue by zacharyarnaise** [gin-gonic/gin#3755]
Just a heads up to inform you that prior to version 0.17.0, `golang.org/x/net` is subject to the following vulnerability:
- CVE-2023-39325
- https://github.com/golang/go/issues/63417

Looks like the pull request has already been made: https://github.com/gin-gonic/gin/pull/3754
Any maintainer could look into this please? :pray:

Thanks!

**Comment by Zacama** [comment]
@appleboy Could you please pay attention to this problem? Thank you most sincerely.

**Comment by mwillfox** [comment]
This is also breaking our security pipeline. Seems like it needs to be resolved.

**Comment by JanneAalto** [comment]
+1

**Comment by kwenzh** [comment]
the same trouble

**Comment by a-h** [comment]
The security fix was merged in https://github.com/gin-gonic/gin/pull/3774 today, but not released yet.

Tests are failing https://github.com/gin-gonic/gin/actions/runs/6890660139/job/18744176853

I note that the tests are not testing the current Go version (Go 1.21), and the failing test is for a Go version that is no longer supported (Go 1.19). https://endoflife.date/go

There's a PR to fix that - https://github.com/gin-gonic/gin/pull/3693 - but that is failing too. The log is no longer available because it's so old.

However, reading back through the history, it seems like it's a flaky test:

```
=== RUN   TestPathCleanMallocs
    path_test.go:85: 
        	Error Trace:	/home/runner/work/gin/gin/path_test.go:85
        	Error:      	Not equal: 
        	            	expected: float64(698)
        	            	actual  : int(0)
        	Test:       	TestPathCleanMallocs
```

And that the flaky test was a problem in the previous version, it was an issue back in Feb - https://github.com/gin-gonic/gin/pull/3502#issuecomment-1438175835 and it was introduced here https://github.com/gin-gonic/gin/pull/2596

The issue is coming from here:

https://github.com/gin-gonic/gin/blob/bdde009dbbbae890db4e6ffdd252e2b4e63a1b85/path_test.go#L84-L85

https://pkg.go.dev/testing#AllocsPerRun returns a float, but the https://pkg.go.dev/github.com/stretchr/testify/assert#EqualValues package takes an interface. There's a well known case that ARM float to int conversion is not the same as x86. Could be related to that, not sure, I'm just guessing.

**Comment by davidorozcog** [comment]
Any progress on this? Any main issue to follow-up? Thanks

**Comment by a-h** [comment]
The flaky test was (I think) set to be skipped in https://github.com/gin-gonic/gin/commit/fd60a24ab76c3c92955ba253c1f7eda9e4981c3c

I'm back here to this issue because of the new security issue with the protobuf dependency (https://github.com/gin-gonic/gin/commit/0d9dbbb44551a872d30fd89d4d55ba0515d646fd)

Users can work around this issue by executing a `go get -u github.com/gin-gonic/gin@7a865dcf1dbe6ec52e074b1ddce830d278eb72cf` to use the latest commit on the main branch, but...

Tagging a new release would allow Github Dependabot (and other tools that upgrade dependencies) to automatically suggest `go.mod` updates, automatically fixing security vulnerabilities in users's projects. I think that would close this issue.

@RedCrazyGhost, @ssfyn and @appleboy - I spotted that you've all recently committed. Is there a plan to tag a new release?

**Comment by appleboy** [comment]
@a-h Yes. See the 1.10 milestone https://github.com/gin-gonic/gin/milestone/24 I will bump the new version recently.
