### ISSUE TITLE
Router Group No Slash Not Redirecting

### ISSUE THREAD

**Issue by ralph327** [gin-gonic/gin#379]
I have a router group "/place" that has the routes "/" and "/:id/*action".

localhost/place/2/ works, but localhost/place/2 does not work although I believe it should according to the readme.

![image](https://cloud.githubusercontent.com/assets/3886287/8760713/beb0a336-2ce9-11e5-9247-a34860500225.png)

I've tried with RedirectTrailingSlash = true, with RedirectFixedPath = true, with both, with neither and still localhost/place/2 does not redirect.

Am I missing something?

**Comment by javierprovecho** [comment]
I believe is because the structure of the router, that's using a tree.

If your route where like `/place/:id` it would work with both `/place/2` and `/place/2/`.

But because you added `*action`, the router is expecting at least another bar.

If it troubles you, I suggest to declare a handler redirect from `/place/:id` to `/place/:id/*action/`.

**Comment by ralph327** [comment]
Okay. I'll give that a try.

**Comment by ralph327** [comment]
Alright, that works! Awesome. I'll keep this solution in mind for the future.

Thanks!
