### ISSUE TITLE
Cannot get null array json

### ISSUE THREAD

**Issue by tommoholmes** [gin-gonic/gin#392]
Hai, I want to binding array json, this my struct json

``` go
type Login struct {
    Range struct {
        Min int `json:"min"`
        Max int `json:"max"`
    } `json:"range"`
    Title string `json:"title"`
    From int `json:"from"`
    Brand []string `json:"brand"`
}
```

when i send null array is't not working and when I print using 

``` go
fmt.Println(json.Brand == nil)
```

it's false

**Comment by itsjamie** [comment]
I imagine what is happening is that the JSON you're receiving is sending a JSON value of `[]`, which is treated differently than a `null`.

Here is a playground link that shows the default behaviour of Go when dealing with JSON null values in slices rather than `[]`.

http://play.golang.org/p/zVYAKPD-M2

If this isn't your issue, my apologies!
