### ISSUE TITLE
Router panic

### ISSUE THREAD

**Issue by woniu369** [gin-gonic/gin#454]
```go
router.GET("/list-:id-:page", handler) //panic
```
why not support?
```go
router.GET("/list-:id/:page", handler) //pass
```

**Comment by SlinSo** [comment]
Currently this does not work, because "only one wildcard per path segment is allowed".
"-" is not defined as a separator, but you would need to have some kind of defined separator to make this work. One idea is to define every char as a sep that ist not part of regexp[A-Za-z0-9 ]. That way you could possibly have more than one wildcard in a route.

@javierprovecho is that a feature you would like to implement? imho it is not needed, but my apis are quite simple...

```
func TestRouterNotFound(t *testing.T) {
...
	router.GET("/list-:id/:page", func(c *Context) {})
	router.GET("/list2-:id-", func(c *Context) {})
...
		{"/list-123/456/", 301, "map[Location:[/list-123/456]]"},
		{"/list2-123-/", 301, "map[Location:[/list2-123-]]"},
...
```

**Comment by FJM-Slade** [comment]
Hi,
I am having the same problem:
this url "/v1/:part1-:part2/list" retrieves a panic with a message: "panic: only one wildcard per path segment is allowed".
It occurs in gin-gonic:
github.com/gin-gonic/gin.(*node).insertChild(...)
github.com/gin-gonic/gin.(*node).addRoute(...)
