### ISSUE TITLE
Issue in Go get of Gin

### ISSUE THREAD

**Issue by abhisheksingh23** [gin-gonic/gin#475]
Getting this error:

# gopkg.in/bluesuncorp/validator.v5
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:41:17: error: reference to undefined identifier ‘sync.Pool’
 var structPool *sync.Pool
                 ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:331:21: error: reference to undefined identifier ‘sync.Pool’
  structPool = &sync.Pool{New: newStructErrors}
                     ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:331:25: error: expected ‘;’ or ‘}’ or newline
  structPool = &sync.Pool{New: newStructErrors}
                         ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:333:2: error: expected declaration
  return &Validate{
  ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:337:1: error: expected declaration
 }
 ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:352:21: error: reference to undefined identifier ‘sync.Pool’
  structPool = &sync.Pool{New: newStructErrors}
                     ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:352:25: error: expected ‘;’ or ‘}’ or newline
  structPool = &sync.Pool{New: newStructErrors}
                         ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:353:1: error: expected declaration
 }
 ^
../../../gopkg.in/bluesuncorp/validator.v5/validator.go:331:46: error: missing return at end of function
  structPool = &sync.Pool{New: newStructErrors}
                                              ^

**Comment by javierprovecho** [comment]
update to go1.4



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by abhisheksingh23** [comment]
My go version is 1.5.1

**Comment by javierprovecho** [comment]
excuse me then, undefined sync pools is a very common issue for users under go1.3 because sync.pools where introduced in that version.




however I see that the issue come from a dependency, not gin it self.




I'll take a look and give a touch to the owner of that repo.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by abhisheksingh23** [comment]
I reinstalled GO and the problem solved. There might be some installation problems.

**Comment by mttrs** [comment]
I'd like to use go1.5. Any plans to upgrade the go version?

**Comment by lawlite** [comment]
@mttrs I'm using Gin with Go 1.5.1, It works well. Just upgrade Go. There is almost no change to the language(https://golang.org/doc/go1.5).

**Comment by mttrs** [comment]
@lawlite , oh, really!? Then, the dependency file should be updated. 
 https://github.com/gin-gonic/gin/blob/master/Godeps/Godeps.json

But recently no commit and pull request merge. I'm asking this WF updating on the other ticket.
https://github.com/gin-gonic/gin/issues/476

**Comment by EwanValentine** [comment]
I'm having this issue with Go 1.5.1 :'(

**Comment by javierprovecho** [comment]
well, if the error outputs undefined sync pools, then you are not running go1.5.1




i suggest you to run go env and go version, if it still show 1.5, then reinstall go, because there is some old installation making noise in your machine.



NOTE: The information in this e-mail is confidential, being solely for the addressee named above. If you read this message and not the intended recipient, please note that it is completely forbidden any use, disclosure, distribution and / or duplication of this communication without the consent of the sender. If you have received this message in error, please notify us immediately by electronic mail and its elimination.

**Comment by xserv** [comment]
I have same error on centos but not on mac or ubuntu

**Comment by lijinya** [comment]
# github.com/gin-gonic/gin/binding
binding/default_validator.go:29: undefined: validator.Config
binding/default_validator.go:30: too many arguments in call to validator.New
	have (<T>)
	want ()
