### ISSUE TITLE
reconsider a new roadmap?

### ISSUE THREAD

**Issue by johndeng** [gin-gonic/gin#523]
The `Gin` development seems to have returned to normal, Did @manucorporat  reconsider the roadmap formulation, such as v2 things.

**Comment by manucorporat** [comment]
@johndeng In fact I am in the design phase for a possible v2 that fixes most of the design issues of v1 and we have an ace up one's sleeve, Gin v2 could have an experimental execution mode (without changing the api, pluggable) 15x times faster than `net/http`, yes, `x750` faster than martini.

**Comment by johndeng** [comment]
@manucorporat wow! i'm looking forward. It's have a specification date to release the design doc?

**Comment by nazwa** [comment]
Good to see you guys back on the project :+1:

**Comment by no1youknowz** [comment]
> Gin v2 could have an experimental execution mode (without changing the api, pluggable) 15x times faster than net/http, yes, x750 faster than martini.

Damn seriously excited for that!  Looking forward to milestones!  Happy Gin v1 user here!

**Comment by robvdl** [comment]
One thing that would be really nice to see in Gin v2 (though I am not sure if it's possible without mayor rework), is being able to define your own Context struct like gocraft/web does, one thing I don't really like about Gin's context, is that when you put something in the Context in a middleware (like the current logged in user), then pull  it out of the context later in your handler function, you have to cast it back to the correct type... it's really ugly doing that, and something that gocraft/web avoids.

**Comment by javierprovecho** [comment]
For all people who wonder why of this inactivity, some will already know, others don't, so here it goes:

cc #670, #706

Both of us (@manucorporat and me) are working and studying. We try to improve this project on **our spare time**. Sometimes we make a sprint. Others **we just fix critical bugs but Gin is fully stable**. New features and bugs will be reviewed and merged/fixed sometime but I can't guarantee it can be soon (maybe it will, we love the night :smile: ).

Because of our projects and work, we have developed **some cool features** that now are closed source until we adapt them to open source (1). In my case, I'm working with some **new SSE features**, better **graceful router** and **pluggable custom routers** (like regex on /api/my/user but without affecting performance on main router). There is also a lot of features from other projects I would like to borrow like **automatic Let's Encrypt**. And about router performance, I tried to make a fast http version but a lot of thing did broke.

Another question the community asks a lot is to add people to the team so PR can be merged / closed. Right now we can't do that because lack of thrust for a repo with over 7500 stars which **many people and developments teams depend on**.

Hope I have fully explained the current status.

(1): IMO open source is not only publishing just code, it's more about publishing good quality and maintainable source code.

**Comment by appleboy** [comment]
Let's Encrypt has been support in #863
