### ISSUE TITLE
Can you support internal redirect by RedirectTrailingSlashInternal, not 301 by RedirectTrailingSlash

### ISSUE THREAD

**Issue by elsonwu** [gin-gonic/gin#568]
Because I hide the go program under nginx by using proxy_pass, and the go program are under a sub path of our website, for example: 

GET http://www.test.com/api/xxx/
Redirect by 301 to http://www.test.com/xxx

You see you problem, for the go program, its request URI is http://www.test.com/xxx/, not include the /api, so gin redirect to a wrong URL.

So I think if gin support internal redirect will resolve this problem, how do you think about it?

**Comment by widnyana** [comment]
if I'm not miss understand, in python (werkzeug to be specific) I will handle it using this middleware [source](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/contrib/fixers.py#L97)

seems you can use this kind of workaround to solve your problem. otherwise, just ignore this comment :)

I dont know what stack you're using, in my case it work nice in nginx + haproxy with proxy_pass.

**Comment by elsonwu** [comment]
@widnyana I think gin catch the path and redirect before the middleware can see it, right?

Now I use nginx location to hack to remove slash for my API

```
location ~ ^/api/(.+[^/])/?$ {
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:7000/$1?$query_string;
}
```
