### ISSUE TITLE
Binding failed on int required field when value is 0 

### ISSUE THREAD

**Issue by lennon-guan** [gin-gonic/gin#611]
my form struct is like this:

```
type XXX struct {
  Offset int `binding:"required"`
}
```

And my test case is like this:

```
curl http://127.0.0.1:8080/xxx?offset=0
```

**Comment by douglarek** [comment]
You need a `form:"offset"` tag.

**Comment by joeybloggs** [comment]
Is there an error, or is it just passing validation when you would expect it too?

If it's the latter then offset will always exist due to go's a static nature, but could use a pointer to integer and use the "exists" tag instead of "required" more details can be found https://github.com/go-playground/validator/issues/225 even though it's about bool, the same principal applies.

**Comment by appleboy** [comment]
ref: https://godoc.org/gopkg.in/go-playground/validator.v8#hdr-Exists

https://github.com/gin-gonic/gin/issues/690

**Comment by youaresherlock** [comment]
I came across the same problem, got it!
