### ISSUE TITLE
[question] how do I access the fragment section of the request url?

### ISSUE THREAD

**Issue by nexus-uw** [gin-gonic/gin#624]
Hello, 

I have a url in the form 
```http://localhost:5000/oauth2?foo=1#access_token=qwerty```

and a request handler
```go
router.GET("/oauth2", func(c *gin.Context) {
  fmt.Println("Fragment: ",c.Request.URL.Fragment, "URL: ", c.Request.URL.String())
})
```

but when I hit the endpoint with my url, it results in
```
Fragment:  URL: /oauth2?foo=1
```

note: As much as I would prefer, I cant send the access_token as a query param because I do not control the Imugur's OAuth2 service.

**Comment by lawlite** [comment]
This is not an issue of Gin or even Golang. Because browsers do NOT send that to the server.
(You can see that in your browser's developer tools; (Using Chrome) Network-Headers tab.)

https://tools.ietf.org/html/rfc2396#section-4

I think that there is no way, without using JavaScript on the client side.

**Comment by nexus-uw** [comment]
Ahhhh. That makes sense.

Thanks for your help on this.
SR.
