### ISSUE TITLE
Rendering templates, how to make async render 

### ISSUE THREAD

**Issue by bregydoc** [gin-gonic/gin#683]
Hi all, I needed render a template base of a simple dashboard, immediately how a database's petition. The database is lower and delayed about 3 seg and just after i needed render the other template with the new info. But I don't know how to make this. I tried several ways but not work. This is my code, I omitted the database petition and replace with a simple delay:

![image](https://cloud.githubusercontent.com/assets/18302365/17646427/35e75574-618e-11e6-8e65-eee48d2c73b2.png)

**Comment by javierprovecho** [comment]
@bregydoc you may stream a response, but I doubt the html will be parsed before it's complete by any web browser. also, you must use with care a context on a goroutine spawned inside a gin handler. gin doesn't know and/or waits if you spawned one and if you are using its context inside a few seconds later. That's why it will close the writer and the request, and your context will become invalid/closed.

An option is to use a redirect and an iframe in your app, or use a web framework, for processing this behavior directly in the browser.
