### ISSUE TITLE
bug:c.BindJSON(&req)   

### ISSUE THREAD

**Issue by smilesometimes** [gin-gonic/gin#690]
# bug desc

``` go
type UpdateUserReqParameters struct {
    Sender  int    `form:"sender" json:"sender" binding:"required"`
}

code:
var req UpdateUserReqParameters
    if err := c.BindJSON(&req); err != nil {
        response.ErrorResponse(c, http.StatusBadRequest, err)
        return
    }




when i  use  postman  send 
{
    "sender":0,
}

get  this error
r
{err":"Key: 'UpdateUserReqParameters.Sender' Error:Field validation for 'Sender' failed on the 'required' tag"}


```
# I think

the  int 0 in req body can not unmashal.

**Comment by stxml** [comment]
Sender  *int    `form:"sender" json:"sender" binding:"exists"`

**Comment by joeybloggs** [comment]
to further the explanation of @stxml 

`required` only ensures that the value is not set to it's defaut value and because in Go values have a default value, in your case `Sender` will be `0`; you can use exists, with your int being `*int`

please see the documentation [here](https://godoc.org/gopkg.in/go-playground/validator.v8) it outlines all of the tags and descriptions of each.

**Comment by stxml** [comment]
It seems like a common problem. There are several open issues about this exact same thing. 
I think better documentation could help here. The paragraph about 'binding' doesn't even mention that it's using validator, which would have more information.

**Comment by appleboy** [comment]
Answer:

```diff
type UpdateUserReqParameters struct {
-    Sender  int    `form:"sender" json:"sender" binding:"required"`
+    Sender  *int    `form:"sender" json:"sender" binding:"exists"`
}
```

**Comment by YUNZHONGTAN** [comment]
thanks
