### ISSUE TITLE
log.Println() does not print timestamp

### ISSUE THREAD

**Issue by bharatkrishna** [gin-gonic/gin#829]
I am using log.Println() inside the router callback functions to print debug messages. These get printed to console but they don't have timestamps. How do I enable it log timestamps?

**Comment by feute** [comment]
`gin` disables the `log` flags in [debug.go#14](https://github.com/gin-gonic/gin/blob/master/debug.go#L14).

I don't know the reason behind this, rather than hiding the timestamps when printing debug information when calling `debugPrint` [here](https://github.com/gin-gonic/gin/blob/master/debug.go#L43).

But you may enable them as so:

`log.SetFlags(log.LstdFlags)`

Or, including the file and line number:

`log.SetFlags(log.LstdFlags | log.Lshortfile)`

**Comment by bharatkrishna** [comment]
Thanks, it works after I did `log.SetFlags(log.LstdFlags)`. This was what I wanted.

**Comment by peragwin** [comment]
I think this should be reopened. If gin wants to use it's own logging format, it should use its own logger via log.New(). Under no circumstances should it be changing global settings in another package whose behavior others might depend on.

**Comment by appleboy** [comment]
@peragwin @bharatkrishna @philippgille See https://github.com/gin-gonic/gin/pull/1560
