### ISSUE TITLE
Binding required doesn't work why?

### ISSUE THREAD

**Issue by wisnuwardoyo** [gin-gonic/gin#831]
I have struct bellow 
```
type foos struct { Foo string `json:"foo" binding:"required"`}
```

and I have endPoint bellow, 

```
func sendFoo(c *gin.Context) {
    var json *foos

   if err := c.BinJSON(&json); err != nil {
          c.AbortWithStatus(400)
          return
   }
   
    // DO another about foo
}
```

I post JSON to endpoint bellow 
`{"bar":"bar bar"}`

But the err is always nil. 

But when I do 
```
func sendFoo(c *gin.Context) {
    var json foos

   if err := c.BinJSON(&json); err != nil {
          c.AbortWithStatus(400)
          return
   }
   
    // DO another about foo
}
```

the err is not nil.

Why ? Please explain to me.

**Comment by joeybloggs** [comment]
I suspect it is because of how you passed the struct into BindJSON; in your first example you are passing in a pointer to a pointer and the second example is a pointer to a struct.

This line here checks the type https://github.com/gin-gonic/gin/blob/master/binding/default_validator.go#L18 and because the type is not a struct, it always returns nil.

So in your first example remove the `&` when passing the json struct as it is already a pointer.

**Comment by wisnuwardoyo** [comment]
when I remove `&` when passing the json struct it got Json Unmarshall error. But BTW that is right, the validator only accept pointer or a struct. In first example I pass pointer to a pointer to a struct. Should be closed as well
