### ISSUE TITLE
Binding for URL Params

### ISSUE THREAD

**Issue by miketonks** [gin-gonic/gin#846]
Is there a way to validate URL params?

e.g. 

```go
r.GET("/:foo/*bar", myFunc)
```

How can I validate foo and bar?

It would be nice if c.Bind() method could fall back (query params, form params, url params) - maybe introducing a 'url' tag:

```go
type MyParams struct {
    Foo string `url:"foo"`
    Bar string `url:"bar`
    Download bool `form:"dl"`
}
```

**Comment by singggum3b** [comment]
I'm wondering this too ?

**Comment by javierprovecho** [comment]
@miketonks that's an interesting feature, however the bind validator would need the fingerprint of the path, or just try to un marshall the `c.Params(...)` into an struct. need to think about it...

**Comment by thinkerou** [comment]
We can get these value using `c.Param("foo")` and `c.Param("bar")`, but I don't understand we need to validate what? The type of value which got by `c.Param("foo")`, right?

**Comment by plokhikh** [comment]
Will it be implemented? I'm interest it too

**Comment by Szasza** [comment]
@javierprovecho do you happen to have any updates on this one?

**Comment by thinkerou** [comment]
@Szasza can you describe the issue requirement? thanks!

**Comment by Szasza** [comment]
@thinkerou thank you for the ultra-quick response, it is much appreciated.

Use case: having an URL path like `/books/:id`, where ID is let's say an UUID. I would like to be able to use struct-based binding using tags to validate the URL path parameter `id`.

Problem: Currently the above is not possible in a straightforward way, because:
* the `bind` and `shouldBind` functions only exist for query parameters, and request bodies, but not for URL path parameter
* using the context there is no way to mutate the request query or body, which would enable to put the URL params into the request query/body and use the existing binding functions

One workaround I can think of from the top of my head is creating a new http.Request, copying the URL path parameter names and values into the new request's query parameters, and running `bindWith` using that, but it is extra code in each handler which could be simplified.

I hope the above helps.

**Comment by thinkerou** [comment]
@Szasza you are welcome!
`uuid` likes `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`, and uri is `/rest/n/:uuid`, now visit `/rest/n/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` will trigger binding, but how should check it? because input `uuid` is a string. thanks!

**Comment by Szasza** [comment]
@thinkerou I think there is a misunderstanding here, please allow me to clarify it.

When I bind let's say the query parameters of a request, there are two tags that I use for the request struct's fields:
- `form:"id"` - it binds the `id` query param to the struct field
- `binding:"uuid"` - this is a pass-through to `validator.v8`, the value is validated against the [uuid](https://godoc.org/gopkg.in/go-playground/validator.v8#hdr-Universally_Unique_Identifier_UUID) validation rule.

Is it possible to have the same pass-through for the `binding` tag in case of an ``uri:"id"`` binding as well and return a proper validation message instead of a panic? This would be useful since the router does not support regexp-based URI parameter matching.

I hope the above helps, please let me know if further clarification is needed, and thank you again.

**Comment by thinkerou** [comment]
@Szasza thanks!
Now #1612 have supported bind uri params, please help me review, thanks everybody!

**Comment by Szasza** [comment]
@thinkerou my pleasure, thank you for the quick implementation, it is much appreciated :smile:

**Comment by axiaoxin** [comment]
Why not support the type of params specified in URL?

**Comment by thinkerou** [comment]
@axiaoxin IMO, that is too complex.

**Comment by miketonks** [comment]
Thanks for adding this feature, it looks great.

If anyone is interested we solved the problem another way, which can be used on top of / alongside gin validation.

See: https://github.com/miketonks/swag-validator

**Comment by thinkerou** [comment]
#1612 merged!

**Comment by dszakallas** [comment]
Thanks! This is great. Why not add `BindUri` and `MustBindUri` too?

**Comment by halink0803** [comment]
When there will be a new release? This feature is useful and I don't want to fork to the latest commit.

**Comment by thinkerou** [comment]
```
Thanks! This is great. Why not add BindUri and MustBindUri too?
```
@dszakallas I will add it. thanks!

```
When there will be a new release? This feature is useful and I don't want to fork to the latest commit.
```
1.4 version on February 28, 2019, and publish release need to @javierprovecho help.

**Comment by thinkerou** [comment]
@dszakallas #1694 add `BindUri`.

**Comment by halink0803** [comment]
@thinkerou Thank you for quick response, I think we will fork latest commit by then.

**Comment by cappuccino5** [comment]
please there  deal? I too like use it

**Comment by thinkerou** [comment]
@cappuccino5 what's mean?

**Comment by SilkageNet** [comment]
please how bind uri to map

**Comment by zhujinhe** [comment]
Btw, should `Uri` be all uppercase?

**Comment by asbjornu** [comment]
If I want a model to be bound to `form` **and** `uri`, do I need to call several `Bind` methods? Calling `ShouldBind()` doesn't seem to bind `uri` parameters.

**Comment by hrQAQ** [comment]
@asbjornu Maybe you need to try `ShouldBindWith()`
