### ISSUE TITLE
What is the best way to simulate httputil.DumpResponse?

### ISSUE THREAD

**Issue by FrankIT60** [gin-gonic/gin#934]
Hello, someone could show me what the best way to simulate httputil.DumpResponse?
T.i.a
Franco

**Comment by mrichman** [comment]
Simulate it? Are you trying to view the HTTP response before it's sent to the client?

**Comment by FrankIT60** [comment]
exactly. If I dispute the content of the service I would like to have
the evidence of what has been transmitted.

2017-08-11 22:45 GMT+02:00, Mark Richman <notifications@github.com>:

**Comment by javierprovecho** [comment]
@FrankIT60 gin does not use a buffer for the response you can check. A weird way of accomplishing this could be to create a dummy *http.ResponseWriter and make your calls to it, then use httputil and copy to the real response writer...

because you want to "simulate", you can't use the real response writer for that.

reopen if you still have doubts
